version: '2'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WebApiUrlHC=http://webapi:5001/hc
    ports:
      - "80"

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  writemodel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  readmodel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development