apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yarmolovichalex1/frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
        - name: bb
          image: gcr.io/google_containers/busybox
          command:
            - sh
            - "-c"
            - sleep 5; wget -O - ${KUBERNETES_RO_SERVICE_HOST}:${KUBERNETES_RO_SERVICE_PORT}/api/v1/pods/;
              sleep 10000
          ports:
            - containerPort: 8080
          env:
            - name: KUBERNETES_RO_SERVICE_HOST
              value: 127.0.0.1
            - name: KUBERNETES_RO_SERVICE_PORT
              value: '8001'
          volumeMounts:
            - name: test-volume
              mountPath: "/mount/test-volume"
        - name: kubectl
          image: gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
          imagePullPolicy: Always
          args:
            - proxy
            - "-p"
            - '8001'
      volumes:
        - name: test-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  selector:
    app: webapi
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: yarmolovichalex1/webapi
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: writemodel
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: writemodel
    spec:
      containers:
        - name: writemodel
          image: yarmolovichalex1/writemodel
          imagePullPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: readmodel
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: readmodel
    spec:
      containers:
        - name: readmodel
          image: yarmolovichalex1/readmodel
          imagePullPolicy: Always